version: '2'
services:
  demo:
    build: .
    depends_on:
      - mysql
    command: ["/usr/local/bin/wait-for-mysql.sh", "sstest_mysql", "/usr/local/bin/init.sh"]
    container_name: sstest_demo
    ports:
      - "80:80"
    tty: true
  mysql:
    container_name: sstest_mysql
    image: mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: dTRKn3JPWbAAxRE42uE3dkFaJOC7nuT9
      MYSQL_DATABASE: notes_app
      MYSQL_USER: notes_app_user
      MYSQL_PASSWORD: JGx05CWMKBmCWit7xfZjbrkYlMwX1b2F
  memcache:
    container_name: sstest_memcache
    image: memcached
    ports:
      - "11211:11211"
